---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ocpawssecret-pvc
  labels:
    app: ocpawssecret
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APP_NAME}
  generation: 1
  labels:
    app: ${APP_NAME}    
spec:
  progressDeadlineSeconds: 600
  replicas: ${REPLICAS}
  revisionHistoryLimit: 10 
  selector:
    matchLabels:
      app: ${APP_NAME}           
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: ${APP_NAME}
        deployment: ${APP_NAME}      
    annotations:
        sidecar.istio.io/proxyCPU: "10m"
        sidecar.istio.io/proxyMemory: "24Mi"        
    spec:
      # ensure the scheduler distributes replicas evenly on the worker nodes
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                      - ${APP_NAME}
                topologyKey: "kubernetes.io/hostname"
      containers:     
      - envFrom:
          - configMapRef:
              name: config-env-${APP_NAME}
        image: ocpawssecret:1.0
        imagePullPolicy: Always
        securityContext:
          privileged: false
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - all
            add: ["NET_ADMIN", "SYS_TIME"]
        name: ${APP_NAME}
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          exec:
            command: ['${READINESSPROBE}']
          initialDelaySeconds: 30
        resources:
          limits:
            cpu: ${LIMITS_CPU}
            memory: ${LIMITS_MEMORY}Gi
          requests:
            cpu: ${REQUESTS_CPU}
            memory: ${REQUESTS_MEMORY}Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: ocpawssecret-persistent-storage
          mountPath: "/usr/application/"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroupChangePolicy: "OnRootMismatch"
      terminationGracePeriodSeconds: 30
      volumes:        
        - name: ocpawssecret-persistent-storage
          persistentVolumeClaim:
            claimName: ocpawssecret-pvc
