apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ocpawssecret
  labels:
    app: ocpawssecret
spec:
  hosts:
  - "*"
  gateways:
  - "istio-intranet/intranet-gateway"
  http:
  - match:
    - uri:
        prefix: /ocpawssecret
    route:
    - destination:
        port:
          number: 80
        host: ocpawssecret.defalt.svc.cluster.local
